buildreports/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required
import views


urlpatterns = patterns('',
                       url(r'^$', views.index, name='index'),
                       url(r'^all/$',
                           login_required(views.allview),
                           name='allview'),
                       url(r'^history/(?P<buildreportid>\d+)/$',
                           login_required(views.history), name='history'),
                       url(r'^edit/(?P<buildreportid>\d+)/$',
                           login_required(views.editview), name='edit'),
                       url(r'^view/(?P<buildreportid>\d+)/$',
                           views.viewmode, name='view'),
                       url(r'^view/(?P<buildreportid>\d+)/all/$',
                           views.viewmode_all, name='view_all'),
                       url(r'^view_sr/(?P<buildreportid>\d+)/$',
                           views.suitereport_viewmode, name='view'),
                       # url(r'^id/(?P<runid>\d+)/$', login_required(views.runinfo), name='runinfo'),
                       # url(r'^finished/after/(?P<date>.+)/$', login_required(views.searchafter), name='searchafter'),
                       # url(r'^bug/like/(?P<bugid>.+)/$', login_required(views.searchbug), name='searchbug'),
                       )

cattle/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.auth.decorators import login_required
from django.contrib import admin
from buildreports import views
from commits.views import list
urlpatterns = patterns('',
                       url(r'^$', list, name='root'),
                       url(r'^branches/', include('branches.urls', namespace='branchesview')),
                       url(r'^commits/', include('commits.urls', namespace='commitsview')),
                       url(r'^buildreports/', include('buildreports.urls', namespace='buildreportsview')),
                       url(r'^sitreps/', include('sitreps.urls', namespace='sitrepsview')),
                       url(r'^runs/', include('runs.urls', namespace='runsview')),
                       url(r'^tests/', include('tests.urls', namespace='testsview')),
                       url(r'^admin/', include(admin.site.urls)),
                       url(r'^builders/', include('builders.urls', namespace='builders')),
                       url(r'^accounts/', include('accounts.urls', namespace='accounts')),
                       url(r'^logparser/', include('logparser.urls', namespace='logparser')),
                       )

runs/urls.py
from django.conf.urls import patterns, url, include
from django.contrib.auth.decorators import login_required
from rest_framework.urlpatterns import format_suffix_patterns
from runs import views

urlpatterns = patterns('',
                       url(r'^rest/(?P<myrun>.*)$', views.api_root, name="rest"),
                       url(r'^$', views.index, name='index'),
                       url(r'^history/(?P<runid>\d+)/$', login_required(views.history), name='history'),
                       url(r'^bycommit/(?P<commit>\d+)/$', login_required(views.commitinfo), name='bycommit'),
                       url(r'^edit/(?P<runid>\d+)/$', login_required(views.editview), name='edit'),
                       url(r'^id/(?P<runid>\d+)/$', views.runinfo, name='runinfo'),
                       url(r'^builder/(?P<host>.*)/$', views.hostinfo, name='runinfo'),
                       url(r'^search/$', views.search_branch, name='search_branch'),
                       )

# Login and logout views for the browsable API
urlpatterns += [url(r'^api-auth/$',
                    include('rest_framework.urls',
                            namespace='rest_framework')),
                ]

buildreports/models.py
from django.db import models
from builders.models import Builder
from branches.models import Branch
from simple_history.models import HistoricalRecords
# Create your models here.


class Buildreport(models.Model):
    history = HistoricalRecords()
    title = models.CharField(max_length=128)
    description = models.CharField(max_length=512)
    branch = models.ForeignKey(Branch, null=True, blank=True)
    builders = models.ManyToManyField(Builder, null=True, blank=True)

    private = models.BooleanField(default=False)
    marked_for_removal = models.BooleanField(default=False)
    username = models.CharField(max_length=128, default="Automatic")
    entrytype = models.CharField(max_length=128, default="Automatic")

    def __str__(self):              # __unicode__ on Python 2
        return str(self.title)

buildreports/forms.py
from django.forms import ModelForm, Textarea, SelectMultiple
from models import Buildreport


class BuildreportEdit(ModelForm):

    class Meta:
        model = Buildreport
        fields = [
            'title',
            'description',
            'private',
            'marked_for_removal',
            'branch',
            'builders']
        widgets = {
            'description': Textarea(attrs={'cols': 30, 'rows': 10}),
            'builders': SelectMultiple(),
        }

buildreports/views.py
import time
from django.http import HttpResponse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render_to_response
from django.shortcuts import loader, render
from django.template import RequestContext
from django.http import HttpResponseRedirect

from models import Buildreport
from forms import BuildreportEdit
from runs.models import Run
from commits.models import Commit

ENTRIES_PER_PAGE = 10  # effects paginated views in this file

REPORTS_PER_PAGE = 20  # effects paginated views in this file

# Create your views here.


def index(request):
    public_list = Buildreport.objects.filter(
        private=False).filter(
        marked_for_removal=False)

    userreport_list = Buildreport.objects.filter(
        username=request.user).filter(
        private=True).filter(
            marked_for_removal=False)

    Buildreport_list = userreport_list | public_list

    Buildreport_list = Buildreport_list.order_by("-private")

    paginator = Paginator(Buildreport_list, REPORTS_PER_PAGE)

    if request.GET.get('makenew') == "true":
        newreport = Buildreport(
            title="new report",
            description="",
            private=False,
            username=str(request.user),
            entrytype="Creation"
        )
        newreport.save()
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

    page = request.GET.get('page')
    try:
        buildreports = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        buildreports = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        buildreports = paginator.page(paginator.num_pages)

    return render_to_response(
        'buildreports/index.html', {"buildreports": buildreports, "request": request})


def allview(request):
    Buildreport_list = Buildreport.objects.all()
    paginator = Paginator(Buildreport_list, REPORTS_PER_PAGE)

    page = request.GET.get('page')
    try:
        buildreports = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        buildreports = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        buildreports = paginator.page(paginator.num_pages)

    return render_to_response(
        'buildreports/index.html', {"buildreports": buildreports})


def history(request, buildreportid):
    Buildreport_list = Buildreport.objects.filter(pk=buildreportid)

    # if this is a POST request we need to process the form data
    message = ""

    restorepoint = request.POST.get('restorepoint')
    if restorepoint is not None:
        entry = Buildreport.objects.all().get(pk=buildreportid).history.all()
        if entry:
            for item in entry:
                if restorepoint in str(item):
                    Buildreport_list.update(
                        title=item.title,
                        description=item.description,
                        private=item.private,
                        username=str(request.user),
                        entrytype="Restore"
                    )
                    Buildreport_list[0].save()
                    message += "Restoring to point: " + \
                        str(restorepoint) + " Potentially successful"
                    return HttpResponseRedirect(
                        request.META.get('HTTP_REFERER'))
        else:
            message += "Restore Failed"

    template = loader.get_template('buildreports/history.html')
    context = RequestContext(request, {
        "buildreports": Buildreport_list,
        "message": message,
    })
    return HttpResponse(template.render(context))


def editview(request, buildreportid):
    Buildreport_list = Buildreport.objects.filter(pk=buildreportid)

    message = ""

    form = BuildreportEdit(request.POST or None, instance=Buildreport_list[0])

    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        # now created before und stuff
        # check whether it's valid:
        if form.is_valid():
            Buildreport_list.update(
                title=form.cleaned_data['title'],
                description=form.cleaned_data['description'],
                branch=form.cleaned_data['branch'],
                private=form.cleaned_data['private'],
                marked_for_removal=form.cleaned_data['marked_for_removal'],
                username=str(request.user),
                entrytype="Edit"
            )

            Buildreport_list[0].builders.clear()
            for builder in form.cleaned_data['builders']:
                Buildreport_list[0].builders.add(builder)

            Buildreport_list[0].save()
            # return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
            template = loader.get_template(
                'buildreports/redirect_template.html')
            context = RequestContext(request, {
                'redirect_url': "/buildreports/"
            })
            return HttpResponse(template.render(context))
        else:
            message = "invalid input, please adjust."

    template = loader.get_template('buildreports/edit.html')
    context = RequestContext(request, {
        "buildreport": Buildreport_list[0],
        "message": message,
        "form": form.as_p,
    })
    return HttpResponse(template.render(context))


def viewmode(request, buildreportid):
    start = time.clock()
    Buildreport_list = Buildreport.objects.filter(pk=buildreportid)

    related_runs = Run.objects.filter(
        parent_branch=Buildreport_list[0].branch).select_related()

    related_runtime = str(time.clock() - start)

    specific_runs = Run.objects.none()
    for mybuilder in Buildreport_list[0].builders.all():
        specific_runs = specific_runs | related_runs.filter(builder=mybuilder)
    related_runs = specific_runs.order_by('-end_time')

    specific_runtime = str(time.clock() - start - float(related_runtime))

    commitlist = specific_runs.values("commit").distinct().order_by("-commit")

    # commitlist=Commit.objects.all().order_by('-revision')

    # for mycommit in commitlist:
    #    if len(related_runs.filter(commit__pk = mycommit.pk)) == 0:
    #        commitlist = commitlist.exclude(revision = mycommit.revision)

    paginator = Paginator(commitlist, ENTRIES_PER_PAGE)

    commit_runtime = str(
        time.clock() -
        start -
        float(related_runtime) -
        float(specific_runtime))

    page = request.GET.get('page')
    try:
        commitlist = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        commitlist = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        commitlist = paginator.page(paginator.num_pages)

    final_runs = Run.objects.none()

    for commit in commitlist:
        final_runs = final_runs | specific_runs.filter(
            commit__revision=commit["commit"])

    final_runs = final_runs.order_by('-end_time')

    template = loader.get_template('buildreports/buildreport.html')
    end = time.clock()
    context = RequestContext(
        request,
        {
            "buildreports": Buildreport_list[0],
            "runs": final_runs,
            "commits": commitlist,
            "request": request,
            "loadtime": "a total of " +
            str(
                end -
                start) +
            " Seconds, " +
            related_runtime +
            " Seconds of which was on pulling related runs, " +
            specific_runtime +
            " Seconds of which was on specific run calculations, then commit filtering took an additional " +
            commit_runtime,
        })
    return HttpResponse(template.render(context))


def viewmode_all(request, buildreportid):
    start = time.clock()
    Buildreport_list = Buildreport.objects.filter(pk=buildreportid)

    related_runs = Run.objects.filter(
        parent_branch=Buildreport_list[0].branch).select_related()

    related_runtime = str(time.clock() - start)

    specific_runs = Run.objects.none()
    for mybuilder in Buildreport_list[0].builders.all():
        specific_runs = specific_runs | related_runs.filter(builder=mybuilder)
    related_runs = specific_runs.order_by('-end_time')

    specific_runtime = str(time.clock() - start - float(related_runtime))

    commitlist = specific_runs.values("commit").distinct().order_by("-commit")

    # commitlist=Commit.objects.all().order_by('-revision')

    # for mycommit in commitlist:
    #    if len(related_runs.filter(commit__pk = mycommit.pk)) == 0:
    #        commitlist = commitlist.exclude(revision = mycommit.revision)

    paginator = Paginator(commitlist, commitlist.count())

    commit_runtime = str(
        time.clock() -
        start -
        float(related_runtime) -
        float(specific_runtime))

    final_runs = Run.objects.none()

    for commit in commitlist:
        final_runs = final_runs | specific_runs.filter(
            commit__revision=commit["commit"])

    final_runs = final_runs.order_by('-end_time')

    template = loader.get_template('buildreports/buildreport.html')
    end = time.clock()
    context = RequestContext(
        request,
        {
            "buildreports": Buildreport_list[0],
            "runs": final_runs,
            "commits": commitlist,
            "request": request,
            "donotrefresh": True,
            "loadtime": "a total of " +
            str(
                end -
                start) +
            " Seconds, " +
            related_runtime +
            " Seconds of which was on pulling related runs, " +
            specific_runtime +

buildreports/templates/buildreports/buildreport.html
{% extends "base_template.html" %}
{% load views_extras %}
{% block title %}{{buildreports.title}}: Build Report{% endblock %}

{% block styles %}
<style>
iframe.b-iframe {
  height: 40em;
  width: 50em;
  }
</style>
<style>
    .required label:after {
    color: #e32;
    content: ' *';
    display:inline;
    }
    .required { font-weight: bold; }
</style>
{% endblock %}

{% block headscripts %}
{% endblock %}


{% block content %}
<h1 style="margin-bottom: -.5em;">{{buildreports.title}}: Build Report</h1>
{% if request.user.is_authenticated %}
    <p style = "float:right;">Welcome, {{ request.user.get_username }}. Thanks for logging in. (<a href="/accounts/logout/">Logout</a>)</p>
{% else %}
    <p style = "float:right;"><a href="/accounts/login/">Please log in.</a></p>
{% endif %}
<center>
<div class = "navbar" style="margin-left: 40%;">
<ul class="pagination pagination-content">
        {% if commits.has_previous %}
            <li class="pagination-control"><a href="?page={{ commits.previous_page_number }}">Prev</a></li>
        {% endif %}
            <li><a>Page {{ commits.number }} of {{ commits.paginator.num_pages }}</a></li>
        {% if commits.has_next %}
            <li class="pagination-control"><a href="?page={{ commits.next_page_number }}">Next</a></li>
        {% endif %}
</ul>
</div>
</center>
<div class="table" style="background-color:#eee;font-size:16px;">
  <div class="header" style="background:#eee;">
    <div class="cell headelement" style="color:black;">Commit</div>
    <!--this is where builder collumn headers are generated-->
    {% for builder in buildreports.builders.all %}
    <div class="cell" style = "min-width:345px;width:345px;padding-left:0em;color:black;">{{builder.address|getbuilderstate|safe}}</div>
    {% endfor %}
   </div>
   <div class= "rowGroup">
{% for commit in commits %}
    <div class="row" style="height:4px;" ><!--This is the white seperator between commits for commit of {{commit.commit}} --></div>
    <div class="row">
    <!--this is where commit information is rendered left side-->
    <div class="cell header headelement">
    <a href="http://fisheye.yourdomain.com/changelog/RNA?cs={{commit.commit}}">{{commit.commit}}</a>
    <div>{{commit.commit.bug}}</div>
    </div>
    <!--this is where run reports are rendered-->
    {% for builder in buildreports.builders.all %}
    <div class="cell" style="padding-left:0em;vertical-align:top;background-color:white;">
    
    <div class="table" style="width:100%;">
    {% for run in runs %}{% if run.builder = builder and run.commit.revision = commit.commit%}

    <div class="row {{ run.run_results|translate_PF_class }}{% if run.run_results == 0 and run.caused_bug == ""%} TBD{% endif %}" {%if run.comment|length = 0 and run.caused_bug|length = 0 %} style="height:70px;"{%endif%}>
    <div class="cell">{{run.end_time|date:"d M"}} Len: {{run.end_time|subtractdate:run.start_time|format_time}} Bld:<a href = "{% if "http://" in run.builder.address%}{{run.builder.address}}/builds/{{run.build_number}}{% else %}http://cowtracks.yourdomain.com/view/{{run.builder.address}}/{{run.build_number}}{% endif %}" target = "_EMPTY">{{run.build_number}}</a>
    <br>STE: {{run.suite_file|address_tail}}
    PF:<a href = "/tests/run/{{run.pk}}/">{{run.run_results|translate_PF}}</a>
    <br>OS: {% if run.operating_system == "NA" %}Logged upon completion.{% else %}{{run.operating_system}}{% endif %}
    
    <button class = "alignright" id="my-edit-button-{{run.pk}}">Edit</button>{% if run.history.all.count > 1 %} <button class = "alignright" id="my-history-button-{{run.pk}}">Hist</button> {% endif %}
    </div>
    </div>
    <div class="row {{ run.run_results|translate_PF_class }}{% if run.run_results == 0 and run.caused_bug == ""%} TBD{% endif %}" >
    <div class="cell">{{run.caused_bug|jira_pull_br|safe}}</div>
    </div>
    <div class="row {{ run.run_results|translate_PF_class }}{% if run.run_results == 0 and run.caused_bug == ""%} TBD{% endif %}" >
    <div class="cell">{% if run.comment != "" %} <b>Comment:</b> {% endif %}{{run.comment|linebreaks}} {% if run.comment != "" %} ~{{ run.username }} {% endif %}</div>
    </div>
    <div class="row" style="height:2px;" ><!--This is the white seperator between entries--></div>
    {% endif %}{% endfor%}
    </div>
    </div>
    {% endfor %}
    </div>
{% endfor %}  
    </div> 
</div>
<center>
<div class = "navbar">
<ul class="pagination pagination-content">
        {% if commits.has_previous %}
            <li class="pagination-control"><a href="?page={{ commits.previous_page_number }}">Prev</a></li>
        {% endif %}
            <li><a>Page {{ commits.number }} of {{ commits.paginator.num_pages }}</a></li>
        {% if commits.has_next %}
            <li class="pagination-control"><a href="?page={{ commits.next_page_number }}">Next</a></li>
        {% endif %}
</ul>
</div>
</center>
{% if loadtime %}<br><br>
Initial Data Load took {{loadtime}} Seconds, remaining loadtime can be attributed primarily to JIRA pulls.
{% endif %}
{% endblock %}

{% block footscripts %}
<script>    
{% for run in runs %}
;(function($) {
        $(function() {
            $('#my-edit-button-{{run.pk}}').bind('click', function(e) {
                e.preventDefault();
                $('#edit_pop_up').bPopup({
            content:'ajax',
            contentContainer:'.content',
            loadUrl: '/runs/edit/{{run.pk}}/' //Uses jQuery.load()
            });
            });
         });
     })(jQuery);
;(function($) {
        $(function() {
            $('#my-history-button-{{run.pk}}').bind('click', function(e) {
                e.preventDefault();
                
                $('#edit_pop_up').bPopup({
            content:'ajax',
            contentContainer:'.content',
            loadUrl: '/runs/history/{{run.pk}}/' //Uses jQuery.load()
            });
            });
         });
     })(jQuery);
{% endfor %}
</script>
<script>
function highlight_class(myClass) {
    
    var index;
var a = document.getElementsByClassName(myClass);
for (index = 0; index < a.length; ++index) {
    a[index].className = a[index].className + " HIGHLIGHT";
    console.log('<!-- Highlighting '+index+'-->');
}

}

function unhighlight_class(myClass) {
    
    var index;
var a = document.getElementsByClassName(myClass);
for (index = 0; index < a.length; ++index) {
    a[index].className = a[index].className.replace(" HIGHLIGHT", "");;
    console.log('<!-- Unhighlighting '+index+'-->');
}

}
</script>
{% if donotrefresh %}
<!-- no auto-refresh on this page by request -->
{%else%}
<script>
<!--

/*
Auto Refresh Page with Time script
By JavaScript Kit (javascriptkit.com)
Over 200+ free scripts here!
*/

//enter refresh time in "minutes:seconds" Minutes should range from 0 to inifinity. Seconds should range from 0 to 59
var limit="5:00"

if (document.images){
var parselimit=limit.split(":")
parselimit=parselimit[0]*60+parselimit[1]*1
}
function beginrefresh(){
if (!document.images)
return
if (parselimit==1)
window.location.reload()
else{ 
parselimit-=1
curmin=Math.floor(parselimit/60)
cursec=parselimit%60
if (curmin!=0)
curtime=curmin+" minutes and "+cursec+" seconds left until page refresh!"
else
curtime=cursec+" seconds left until page refresh!"
window.status=curtime
setTimeout("beginrefresh()",1000)
}
}

window.onload=beginrefresh
//-->
</script>
{% endif %}
{% endblock %}

buildreports/templates/buildreports/edit.html
{% load views_extras %}
<html>
<head>
<link rel="stylesheet" type="text/css" href="/static/css/basicviewscheme.css">   
<!-- BEGIN syntax highlighter -->
	<script type="text/javascript" src="/static/js/sh/shCore.js"></script>
	<script type="text/javascript" src="/static/js/sh/shBrushJScript.js"></script>
	<link type="text/css" rel="stylesheet" href="/static/js/sh/shCore.css"/>
	<link type="text/css" rel="stylesheet" href="/static/js/sh/shThemeDefault.css"/>
    <link href="/static/css/multi-select.css" media="screen" rel="stylesheet" type="text/css">
	<script type="text/javascript">
		SyntaxHighlighter.all();
	</script>
	<!-- END syntax highlighter -->

	<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
	<script type="text/javascript" src="/static/js/jquery.searchabledropdown-1.0.8.min.js"></script>
	
	
	<script type="text/javascript">
		$(document).ready(function() {
			$("#id_branch").searchable();
		});
	
	
		// demo functions
    $(document).ready(function() {
        $("#id_branch").searchable({
            maxListSize: 500,						// if list size are less than maxListSize, show them all
            maxMultiMatch: 100,						// how many matching entries should be displayed
            exactMatch: false,						// Exact matching on search
            wildcards: true,						// Support for wildcard characters (*, ?)
            ignoreCase: true,						// Ignore case sensitivity
            latency: 200,							// how many millis to wait until starting search
            warnMultiMatch: 'top {0} matches ...',	// string to append to a list of entries cut short by maxMultiMatch 
            warnNoMatch: 'no matches ...',			// string to show in the list when no entries match
            zIndex: '1000000'							// zIndex for elements generated by this plugin
        });
    });
	</script>
    
</head>
<body>


{% if form%}
<div style="padding:1em;">
<form action="/buildreports/edit/{{buildreport.pk}}/" method="post">
    {% csrf_token %}
    {{form}}
    <input type="submit" value="Save Changes" />
</form>
</div>
{% endif %}




</body>
<footer>
<script src="/static/js/jquery.multi-select.js" type="text/javascript">
</script>

<script type="text/javascript">
//$('#id_builders').multiSelect()
</script>
</footer>
</html>

buildreports/templates/buildreports/history.html
{% load views_extras %}
<html>
<head>
<link rel="stylesheet" type="text/css" href="/static/css/navbar.css">
<link rel="stylesheet" type="text/css" href="/static/css/basicviewscheme.css">       
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
    <script src="/static/js/jquery.bpopup.min.js"></script> 
</head>
<body>

<center>
<div>
{{message}}
</div>


<!-- Edit mode pop up holder-->

<div style="left: 275.5px; position: absolute; top: 1950px; z-index: 9999; opacity: 1; display: block; height: auto; width: 80%;" id="edit_pop_up">
        <div style="height: auto; width: auto; background-color:white;" class="content"></div>
</div>
    
    
<h5>Note:Branch and Builders can only be changed in edit view, and Buildreports can only be deleted from admin.</h5>
    
<div class="table">
  <div class="header">
    <div class="cell">title</div>
    <div class="cell" style = "min-width:200px;">description</div>
    <div class="cell">Type</div>
    <div class="cell" >Entry Type</div>
    <div class="cell" >Username</div>
    
    {#<div class="cell">Restore</div>#}
    
  </div>
  <div class="rowGroup"> 
    {% for buildreportset in buildreports %}
    {% for buildreport in buildreportset.history.all %}
    <div class="row" style="height:2px;"><!--This is the white seperator between entries--></div>
    <div class="row PASS }}">    
        {# Each "buildreport" is a buildreport model object. #}
        <div class = "cell">{{ buildreport.title }}</div>
        <div class = "cell">{{ buildreport.description|linebreaks }}</div>
        <div class = "cell">{% if buildreport.private %} Private {% else %} Public {% endif%}</div>
        <div class = "cell">{{buildreport.entrytype}}</div>
        <div class = "cell">{{buildreport.username}}</div>
        {% if 0 %}
        {# if 0 blocks the restore button from rendering #}
        <div class = "cell">
        
        {% if buildreport != buildreportset.history.all.0%}        
            <form action="/buildreports/history/{{buildreportset.pk}}/" method ="post"> 
                {% csrf_token %}
                <input type="hidden" name="restorepoint" value="{{ buildreport }}" >
                <input type="submit" value="Restore" />
            </form>
        {% else %}
            
        {% endif %}
        </div>
        {% endif %}
       
    </div>
    
    {% endfor %}
    {% endfor %}

  </div>
</div>

</center>

</body>
<footer>
<script>
    
;(function($) {
        $(function() {
            $('#my-edit-button').bind('click', function(e) {
                e.preventDefault();
                $('#edit_pop_up').bPopup({
            contentContainer:'.content',
            loadUrl: '/buildreports/edit/{{buildreports.0.pk}}/' //Uses jQuery.load()
            });
            });
         });
     })(jQuery);
     
</script>
</footer>
</html>

buildreports/templates/buildreports/redirect_template.html
<html>
    <head>
        <script>
            window.top.location.href = '{{ redirect_url }}';
        </script>
    </head>
    <body>Redirecting to <a href="{{redirect_url}}" target="_TOP">{{ redirect_url }}</a></body>
</html>